version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./foxglove_layouts:/foxglove/layouts
      - ./foxglove_data:/foxglove/data
    restart: unless-stopped
